class ConfigSettings:
    POINTS_FOR_ALL_SAVING_GROUPS = 0
    POINTS_FOR_RANDOM_SAVING_GROUPS = 1
    POINTS_FOR_LARGEST_SAVING_GROUPS = 2
    POINTS_TIE_RANDOM_SAVING_GROUPS = 0
    POINTS_TIE_ALL_SAVING_GROUPS = 1
    SEND_MESSAGES_TO_ALL_GROUPS = True
    SEND_MESSAGES_TO_ONLY_OWN_GROUP = False
    SEND_MESSAGES_AND_PERFORM_ACTION = True
    SEND_MESSAGE_OR_PERFORM_ACTION = False
    SLEEP_ON_ALL_GRIDS = True
    SLEEP_ONLY_ON_CHARGING_GRIDS = False
    points_for_saving_survivors = POINTS_FOR_ALL_SAVING_GROUPS
    points_for_saving_survivors_tie = POINTS_TIE_ALL_SAVING_GROUPS
    handling_messages = SEND_MESSAGES_AND_PERFORM_ACTION
    send_messages_to_all_groups = SEND_MESSAGES_TO_ALL_GROUPS
    sleep_everywhere = SLEEP_ON_ALL_GRIDS
